# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool

#组件参数配置
inputs:
  name: ${name}_scf
  namespace: default
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou # 函数所在区域，默认广州
  description: This is a function in ${app} application.
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    - timer: # 每日任务触发器
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer: # 天选抽奖触发器
        parameters:
          name: LiveLotteryTask
          cronExpression: "0 0 */4 * * * *"
          enable: true
          argument: LiveLottery
    - timer: # 自动取关
        parameters:
          name: UnfollowBatchedTask
          cronExpression: "0 0 0 * * MON *"
          enable: false
          argument: UnfollowBatched
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: innersign=0; buvid3=696F898E-CE1D-D669-6A43-99A9C33864A244924infoc; b_nut=1664626244; i-wanna-go-back=-1; b_ut=7; b_lsid=110931079A_1839374C289; _uuid=458910866-B23F-61710-28B10-77EA7779E66946291infoc; buvid4=378F74CB-A959-8674-65F6-C7C113FCD45947444-022100120-8RUqDVYFgen5VdR6eO6hfQ%3D%3D; fingerprint=ce656cffff89fb089eb8f2543e93f2ff; buvid_fp=696F898E-CE1D-D669-6A43-99A9C33864A244924infoc; buvid_fp_plain=undefined; SESSDATA=01b0588f%2C1680178325%2C7b94d%2Aa1; bili_jct=447f44ee0b7679616bcf25040b02d45d; DedeUserID=252092263; DedeUserID__ckMd5=c08d163fa2cd002e; sid=ogv3j80b # cookie，必填
